Repository DNNCommunity/Dnn.StructuredContent, pull requests merged in 2021-09, with the labels that each got.

#9 Changes the packages references to nuget
  .gitignore
  Dnn.StructuredContent.csproj
  packages.config
  web.Debug.config
  web.Release.config
  web.config
Labels: build

#22 Update SqlDataProvider script to support minimum DNN requirements
  DBScripts/0.0.1.SqlDataProvider
Labels: enhancement

#23 Adds a basic build system
  .gitignore
  .nuke/build.schema.json
  .nuke/parameters.json
  DBScripts/00.01.00.SqlDataProvider
  Dnn.StructuredContent.csproj
  Dnn.StructuredContent.sln
  GitVersion.yml
  License.html
  build.cmd
  build.ps1
  build.sh
  global.json
  manifest.dnn
  readme.md
Labels: build

#24 Adds the build files that were ignored
  .gitignore
  Dnn.StructuredContent.csproj
  build/.editorconfig
  build/Build.cs
  build/Configuration.cs
  build/Directory.Build.props
  build/Directory.Build.targets
  build/Helpers.cs
  build/Properties/launchSettings.json
  build/_build.csproj
  build/_build.csproj.DotSettings
Labels: build

#25 Correct messaging on delete content type modal
  app/content-types/delete/template.html
Labels: enhancement

#28 Setup initial module.web project based on Stencil
  .gitignore
  module.web/.editorconfig
  module.web/.gitignore
  module.web/.prettierrc.json
  module.web/LICENSE
  module.web/package-lock.json
  module.web/package.json
  module.web/readme.md
  module.web/src/.eslintrc.json
  module.web/src/components.d.ts
  module.web/src/components/sample-component/readme.md
  module.web/src/components/sample-component/sample-component.scss
  module.web/src/components/sample-component/sample-component.tsx
  module.web/src/index.html
  module.web/src/index.ts
  module.web/src/utils/utils.spec.ts
  module.web/src/utils/utils.ts
  module.web/stencil.config.ts
  module.web/tsconfig.json
Labels: enhancement

#29 Correct TODO typo
  DAL/SQLHelper.cs
Labels: enhancement

#30 Rename DB tables to use underscores instead of dots
  DAL/StructuredContent.dbml
  DAL/StructuredContent.designer.cs
  DBScripts/00.01.00.SqlDataProvider
Labels: enhancement

#31 Created deploy and ci build targets
  .github/workflows/build.yml
  .gitignore
  .nuke/build.schema.json
  Dnn.StructuredContent.csproj
  build/Build.cs
  build/Properties/launchSettings.json
  module.web/package-lock.json
Labels: build

#32 Fixes error in build Restore target
  .gitignore
  .nuke/build.schema.json
  Dnn.StructuredContent.csproj
  build/Build.cs
  packages.config
Labels: build

#33 Adds build results checksum
  build/Build.cs
Labels: build

#34 Adjusted build to package before generating the release notes
  build/Build.cs
Labels: build

#35 Added mergeable to enforce milestones and labels
  .github/mergeable.yml
  Dnn.StructuredContent.csproj
Labels: build

#36 Created config for dependabot
  .github/dependabot.yml
Labels: maintenance

#40 Added some documentation about releasing
  readme.md
Labels: documentation

#45 Fixed a bug that prevented the default/required Name field from appearing in the ContentType designer
  Controllers/ContentTypeController.cs
  app/content-types/edit/template.html
Labels: bug

#47 Update custom table prefix
  DAL/Relationship.cs
  DAL/SQLHelper.cs
  app/content-types/add/template.html
  app/content-types/edit/template.html
Labels: enhancement

#49 Enhanced the Boolean ContentFieldType
  DAL/SQLHelper.cs
  app/content-field-type-options/boolean/controller.js
  app/content-field-type-options/boolean/template.html
  app/content-field-types/boolean/controller.js
  app/content-field-types/boolean/template.html
  app/content-fields/edit/template.html
  app/content-items/edit/controller.js
  app/content-items/edit/template.html
Labels: enhancement

#53 Fixed bug in GetContentItems method
  Controllers/ContentItemController.cs
Labels: bug

#55 Initial implementation of `StyleCop.Analyzers` and global fixes
  .editorconfig
  Controllers/ContentFieldController.cs
  Controllers/ContentFieldTypeController.cs
  Controllers/ContentItemController.cs
  Controllers/ContentTypeController.cs
  Controllers/RelationshipController.cs
  Controllers/RevisionController.cs
  Controllers/VisualizerController.cs
  Controllers/VisualizerTemplateController.cs
  DAL/ContentField.cs
  DAL/Relationship.cs
  DAL/SQLHelper.cs
  DTOs/ContentField.cs
  DTOs/ContentFieldType.cs
  DTOs/ContentItem.cs
  DTOs/ContentType.cs
  DTOs/Relationship.cs
  DTOs/Revision.cs
  DTOs/Visualizer.cs
  DTOs/VisualizerTemplate.cs
  Dnn.StructuredContent.csproj
  Dnn.StructuredContent.sln
  Enums/ContentItemStatus.cs
  Enums/DataType.cs
  ModuleBase.cs
  Properties/AssemblyInfo.cs
  RouteMapper.cs
  Visualizer.ascx.cs
  stylecop.json
Labels: enhancement

#59 Refactored SQLHelper to use Dependency Injection
  Controllers/ContentFieldController.cs
  Controllers/ContentItemController.cs
  Controllers/ContentTypeController.cs
  Controllers/RelationshipController.cs
  Controllers/VisualizerController.cs
  Controllers/VisualizerTemplateController.cs
  DAL/ISQLHelper.cs
  DAL/SQLHelper.cs
  Dnn.StructuredContent.csproj
  RouteMapper.cs
  Startup.cs
Labels: enhancement

#64 Fixed wrong `ObjectQualifier` placement
  DBScripts/00.01.00.SqlDataProvider
Labels: bug

#66 Added templates for issues & PRs
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/help-and-other-questions.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance

#63 Removes syntax that's not Azure-compliant
  DBScripts/00.01.00.SqlDataProvider
Labels: bug

#71 Implemented camelCase serialization
  Controllers/ContentFieldController.cs
  Controllers/ContentFieldTypeController.cs
  Controllers/ContentItemController.cs
  Controllers/ContentTypeController.cs
  Controllers/RelationshipController.cs
  Controllers/RevisionController.cs
  Controllers/Serializers/JsonCamelCaseSerializerAttribute.cs
  Controllers/VisualizerController.cs
  Controllers/VisualizerTemplateController.cs
  DTOs/ContentFieldDto.cs
  DTOs/ContentFieldDtoExtensions.cs
  DTOs/ContentFieldTypeDto.cs
  DTOs/ContentFieldTypeDtoExtensions.cs
  DTOs/RelationshipDto.cs
  DTOs/RelationshipDtoExtensions.cs
  DTOs/RevisionDtoExtensions.cs
  DTOs/VisualizerDto.cs
  DTOs/VisualizerDtoExtensions.cs
  Dnn.StructuredContent.csproj
  Startup.cs
Labels: enhancement

#72 Fixed bugs introduced by changing variable naming format
  Controllers/ContentItemController.cs
  Controllers/ContentTypeController.cs
  Controllers/RelationshipController.cs
  DAL/ISQLHelper.cs
  DAL/SQLHelper.cs
  DTOs/ContentFieldDto.cs
  DTOs/RelationshipDto.cs
  RouteMapper.cs
  app/content-field-types/boolean/directive.js
  app/content-field-types/boolean/template.html
  app/content-field-types/choice/controller.js
  app/content-field-types/choice/directive.js
  app/content-field-types/choice/template.html
  app/content-field-types/date-time/directive.js
  app/content-field-types/date-time/template.html
  app/content-field-types/email/directive.js
  app/content-field-types/email/template.html
  app/content-field-types/number/directive.js
  app/content-field-types/number/template.html
  app/content-field-types/phone-number/directive.js
  app/content-field-types/phone-number/template.html
  app/content-field-types/related-content-multiple/add/controller.js
  app/content-field-types/related-content-multiple/add/template.html
  app/content-field-types/related-content-multiple/delete/controller.js
  app/content-field-types/related-content-multiple/delete/template.html
  app/content-field-types/related-content-multiple/list/controller.js
  app/content-field-types/related-content-multiple/list/directive.js
  app/content-field-types/related-content-multiple/list/template.html
  app/content-field-types/related-content-single/controller.js
  app/content-field-types/related-content-single/directive.js
  app/content-field-types/related-content-single/template.html
  app/content-field-types/static/directive.js
  app/content-field-types/text/directive.js
  app/content-field-types/text/template.html
  app/content-field-types/url/directive.js
  app/content-field-types/url/template.html
  app/content-fields/edit/controller.js
  app/content-fields/service.js
  app/content-items/edit/controller.js
  app/content-items/edit/template.html
  app/content-items/list/controller.js
  app/content-types/delete/controller.js
  app/content-types/delete/template.html
  app/content-types/edit/controller.js
  app/content-types/edit/template.html
  app/content-types/list/controller.js
  app/content-types/list/template.html
  app/relationships/delete/template.html
  app/relationships/edit/controller.js
  app/relationships/edit/template.html
  app/visualizer-templates/delete/controller.js
  app/visualizer-templates/delete/template.html
  app/visualizer-templates/edit/controller.js
  app/visualizer-templates/edit/template.html
  app/visualizer-templates/list/controller.js
  app/visualizer-templates/list/template.html
Labels: bug

#73 Resolved all stylecop warnings
  Controllers/RelationshipController.cs
  DAL/ContentField.cs
  DAL/Relationship.cs
  DAL/SQLHelper.cs
  DTOs/ContentFieldDto.cs
  DTOs/ContentFieldDtoExtensions.cs
  DTOs/ContentFieldTypeDto.cs
  DTOs/ContentFieldTypeDtoExtensions.cs
  DTOs/ContentItemDto.cs
  DTOs/ContentTypeDto.cs
  DTOs/ContentTypeDtoExtensions.cs
  DTOs/RelationshipDto.cs
  DTOs/RelationshipDtoExtensions.cs
  DTOs/RevisionDto.cs
  DTOs/RevisionDtoExtensions.cs
  DTOs/VisualizerDto.cs
  DTOs/VisualizerDtoExtensions.cs
  DTOs/VisualizerTemplateDto.cs
  DTOs/VisualizerTemplateDtoExtensions.cs
  Enums/ContentItemStatus.cs
  Enums/DataType.cs
  ModuleBase.cs
  RouteMapper.cs
  Startup.cs
  Visualizer.ascx.cs
  app.config
Labels: documentation

#76 Fixes display bug when Related Content editor does not have a ContentItem assigned
  app/content-field-types/related-content-multiple/list/controller.js
Labels: bug

#77 Adds 'Allow Other' functionality to all versions of the Choice ContentFieldType
  app/content-field-type-options/choice/controller.js
  app/content-field-type-options/choice/template.html
  app/content-field-types/choice/controller.js
  app/content-field-types/choice/edit/template.html
  app/content-field-types/choice/template.html
  css/ContentLibrary.css
Labels: enhancement

#78 Adds new control types to the numeric ContentFieldType
  app/content-field-type-options/choice/template.html
  app/content-field-type-options/number/controller.js
  app/content-field-type-options/number/template.html
  app/content-field-types/number/controller.js
  app/content-field-types/number/template.html
  app/content-fields/edit/controller.js
  app/content-items/edit/controller.js
  css/ContentLibrary.css
Labels: enhancement

#80 Added mask option to textbox control
  Dnn.StructuredContent.csproj
  ModuleBase.cs
  app/app.js
  app/content-field-type-options/text/controller.js
  app/content-field-type-options/text/template.html
  app/content-field-types/text/controller.js
  app/content-field-types/text/template.html
  app/content-fields/edit/controller.js
  plugins/ngMask/ngMask.js
  plugins/ngMask/ngMask.min.js
  plugins/ngMask/ngMask.min.map
  scripts/ContentLibrary.js
Labels: enhancement
