Repository DNNCommunity/Dnn.StructuredContent, pull requests merged in 2022-03, with the labels that each got.

#133 Enforces a build on windows 2019
  .github/workflows/build.yml
Labels: build

#139 Eraware to dnncommunity
  module.web/package-lock.json
  module.web/package.json
  module.web/src/components/sample-component/sample-component.tsx
  module.web/src/index.ts
  module.web/src/utils/utils.spec.ts
  module.web/src/utils/utils.ts
Labels: dependencies

#140 Fixes
  ModuleBase.cs
  Visualizer.ascx
  Visualizer.ascx.cs
  app/content-field-type-options/boolean/directive.js
  app/content-field-type-options/choice/controller.js
  app/content-field-type-options/choice/directive.js
  app/content-field-type-options/date-time/directive.js
  app/content-field-type-options/email/directive.js
  app/content-field-type-options/number/directive.js
  app/content-field-type-options/phone-number/directive.js
  app/content-field-type-options/static/directive.js
  app/content-field-type-options/text/directive.js
  app/content-field-type-options/url/directive.js
  app/content-field-types/boolean/directive.js
  app/content-field-types/choice/directive.js
  app/content-field-types/date-time/directive.js
  app/content-field-types/email/directive.js
  app/content-field-types/number/directive.js
  app/content-field-types/phone-number/directive.js
  app/content-field-types/related-content-multiple/add/directive.js
  app/content-field-types/related-content-multiple/delete/directive.js
  app/content-field-types/related-content-multiple/list/controller.js
  app/content-field-types/related-content-multiple/list/directive.js
  app/content-field-types/related-content-single/directive.js
  app/content-field-types/service.js
  app/content-field-types/static/directive.js
  app/content-field-types/text/directive.js
  app/content-field-types/url/directive.js
  app/content-fields/service.js
  app/content-items/list/controller.js
  app/content-items/service.js
  app/content-types/edit/controller.js
  app/content-types/list/controller.js
  app/content-types/list/directive.js
  app/content-types/service.js
  app/relationships/service.js
  app/revisions/list/controller.js
  app/revisions/service.js
  app/visualizer-templates/list/controller.js
  app/visualizer-templates/service.js
  app/visualizers/service.js
  app/visualizers/view/controller.js
  app/visualizers/view/directive.js
  scripts/ContentLibrary.js
Labels: enhancement
